name: "TODO"

on: ["push"]

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
        - name: "TODO to Issue"
          uses: "alstr/todo-to-issue-action@v4"
          id: "todo"
          with:
            TOKEN: ${{ secrets.GITHUB_TOKEN }}
